name = "glowback-website"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "out"

[env.production]
vars = { NODE_ENV = "production" }

# KV namespace bindings for production
[[env.production.kv_namespaces]]
binding = "GLOWBACK_COUNTER_KV"
id = "8f4c47532c064285a5efff505a409113"
preview_id = "8f4c47532c064285a5efff505a409113"